name: File Sync

on:
  push:
    branches:
      - main

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@main
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            flash-gordon/polygon@main
          FILES: |
            tool-config.yaml=tool-config-synced.yaml
          TOKEN: ${{ secrets.ACTIONS }}
